# 相关配置说明
  # favicon: 网站图标
  # avatar: 主题用户头像与昵称
  # rss: rss订阅
  # gtag: Google 分析
  # comments: 文章评论系统
    # gitalk
    # disqus
  # navbar: 主题页面导航栏
  # catalog: 文章目录
  # prevnext: 文章末尾的上一页与下一页
  # friends: 友链
  # footer: 页脚信息
  # search: 文章搜索

# enable: 是否开启相应功能，可选true || false

# 网站图标
favicon:
  enable: true
  icon: /images/favicon.png
  touch_icon: /images/favicon.png

# 用户头像与昵称
avatar:
  author_photo: /images/avatar.png
  author_nickname: Oranges
  path: /

# Google 分析
# https://analytics.google.com
# 注册Google分析账号，在管理/创建媒体资源/选择网站/填写相关信息后得到跟踪Id，一般格式为UA-xxxxxxx-x
# 如之前已有注册账号，在管理/跟踪信息/跟踪代码/找到跟踪ID，一般格式为UA-xxxxxxx-x
gtag:
  enable: false
  gtagkey: UA-xxxxxxx-x

# 文章评论系统
comments:
  enable: true
  # 目前仅支持gitalk, valine, disqus评论，选择喜欢的一种开启即可

  gitalk:
    # https://github.com/gitalk/gitalk#usage查看官方教程
    enable: false
    clientID:
    clientSecret:
    repo:
    owner:
    admin:
    id: location.pathname
    distractionFreeMode: false

  valine:
    # https://valine.js.org/quickstart.html#%E8%8E%B7%E5%8F%96APP-ID-%E5%92%8C-APP-Key
    # 进入以上网址查看官方教程
    enable: false
    appId:
    appKey:
    placeholder: Welcome!
    avatar: retro
    vempty_display: false

  # disqus 需科学上网方可使用
  disqus:
    # https://disqus.com/
    # 注册账号，获取shortname.disqus.com，shortname为你定义的唯一name
    # 例：我注册配置完毕后的网址为zxcxxxx.disqus.com，zxcxxxx即为shortname
    enable: false
    shortname: zxcxxxx

# 主题页面导航栏
navbar:
  -
    name: 主页
    enable: true
    path: /
    key: home
  -
    name: 归档
    enable: true
    path: /archives/
    key: archives
  -
    name: 分类
    enable: true
    path: /categories/
    key: categories
  -
    name: 标签
    enable: true
    path: /tags/
    key: tags
  -
    name: 朋友
    enable: true
    path: /friends/
    key: friends
  -
    name: 关于
    enable: true
    path: /about/
    key: about

# 文章目录
catalog:
  enable: true

# 文章末尾的上一页与下一页
prevnext:
  enable: true

# 友链详细信息：支持多个友链
friends:
  # nickname: 昵称
  # site: 地址
  # meta: 描述
  -
    nickname: Zcheng
    site: https://zcheng.site/
    meta:
  -
    nickname: Hexo
    site: https://hexo.io/
    meta:

# 页脚信息
footer:
  # social: 社交方式
  # more: 更多页脚信息
  social:
    # name: 名称
    # icon: 图标，目前仅支持IconFont部分图标
    # path: 地址
    -
      name: github
      icon: github
      path: https://github.com/zchengsite/hexo-theme-oranges
    -
      name: email
      icon: envelope
      path: mscsdfsaw***@163.com
    -
      name: facebook
      icon: facebooksquare
      path:
    -
      name: twitter
      icon: twitter
      path:
    -
      name: 微信
      icon: wechat
      path:
    -
      name: 微博
      icon: weibo
      path:
    -
      # rss需安装 hexo-generator-feed 插件
      # 具体参照https://github.com/hexojs/hexo-generator-feed
      name: rss
      icon: rss
      path: /atom.xml

  more:
    -
      name: Copyright © Oranges 2020
      path: https://github.com/zchengsite/hexo-theme-oranges
    -
      name: Theme by Oranges | Powered by Hexo
      path: https://github.com/zchengsite/hexo-theme-oranges

# 文章搜索
search:
  enable: true
  placeholder: 搜索...
